stages:
#  - test
  - build
  - deploy

#junit:
#  stage: test
#  script:
#    - ./gradlew test

build:
  stage: build
  only:
    - dev
    - master
  script:
    - chmod +x gradlew
    - ./gradlew bootJar
  artifacts:
    paths:
      - /opt/app/spd_talks.jar

deploy develop:
  stage: deploy
  only:
    - dev
  dependencies:
    - build
  script:
    - cd /opt/app
    - ./restart.sh &