stages:
  #  - test
  - build
  - deploy

#junit:
#  stage: test
#  script:
#
#    - ./gradlew test

build:
  stage: build
  only:
    - dev
    - master
  script:
    - chmod +x gradlew
    - ./gradlew bootJar
    - ls -l
  artifacts:
    paths:
      - ./build/libs/spd_talks.jar

deploy dev:
  stage: deploy
  only:
    - dev
  dependencies:
    - build
  script:
    - sudo mv ./build/libs/spd_talks.jar /opt/app
    - cd /opt/app
    - ./dev_restart.sh &