ALTER TABLE chats ALTER COLUMN id TYPE BIGINT;

ALTER TABLE chats_users ALTER COLUMN id TYPE BIGINT;

ALTER TABLE db_users ALTER COLUMN id TYPE BIGINT;

ALTER TABLE user_roles ALTER COLUMN id TYPE BIGINT;